services:
  python-service:
    build:
      context: backend/.
      target: debug
    ports:
      - 8080:8080
      - 5678:5678
    secrets:
      - mongodb_user
      - mongodb_password
      - tmdb_v3_token
      - tmdb_v4_token
    volumes:
      - ./logs:/logs
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0.12
    restart: unless-stopped
    healthcheck:
      test: "mongosh --quiet localhost:27017 --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'"
      start_period: 20s
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_user
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_password
    # ports:
    #   - 27017:27017
    secrets:
      - mongodb_user
      - mongodb_password
    volumes:
      - dbdata:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongo"
      ME_CONFIG_MONGODB_ADMINUSERNAME_FILE: /run/secrets/mongodb_user
      ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: /run/secrets/mongodb_password
      ME_CONFIG_BASICAUTH: "false"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    secrets:
      - mongodb_user
      - mongodb_password

secrets:
  mongodb_user:
    file: ./secrets/mongodb_user_name.txt
  mongodb_password:
    file: ./secrets/mongodb_password.txt
  tmdb_v3_token:
    file: ./secrets/tmdb_v3_token.txt
  tmdb_v4_token:
    file: ./secrets/tmdb_v4_token.txt

volumes:
  dbdata:
